'use client';

import { ChangeEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '../lib/supabase/client';

type EditMode = 'recreate_shoot' | 'preserve_identity' | 'change_outfit' | 'change_scene' | 'localized_edit';
const modes: { value: EditMode; label: string }[] = [
  { value: 'recreate_shoot', label: 'Recriar ensaio' }, { value: 'preserve_identity', label: 'Preservar identidade' },
  { value: 'change_outfit', label: 'Alterar roupa' }, { value: 'change_scene', label: 'Alterar cenário' }, { value: 'localized_edit', label: 'Edição localizada' },
];

export default function Home() {
  const router = useRouter(); const supabase = createClient();
  const [referenceFile,setReferenceFile]=useState<File|null>(null); const [reference,setReference]=useState<string|null>(null);
  const [clientFiles,setClientFiles]=useState<File[]>([]); const [clientPhotos,setClientPhotos]=useState<string[]>([]);
  const [editMode,setEditMode]=useState<EditMode>('recreate_shoot'); const [instructions,setInstructions]=useState(''); const [consent,setConsent]=useState(false);
  const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [resultImage,setResultImage]=useState<string|null>(null);
  useEffect(()=>()=>{if(reference)URL.revokeObjectURL(reference);clientPhotos.forEach(url=>URL.revokeObjectURL(url));},[reference,clientPhotos]);
  function chooseReference(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(reference)URL.revokeObjectURL(reference);setReferenceFile(f);setReference(URL.createObjectURL(f));setMessage('');setResultImage(null)}
  function chooseClientPhotos(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]).slice(0,5);clientPhotos.forEach(url=>URL.revokeObjectURL(url));setClientFiles(files);setClientPhotos(files.map(f=>URL.createObjectURL(f)));setResultImage(null);setMessage(files.length===5&&(e.target.files?.length??0)>5?'Use no máximo 5 fotos da cliente.':'')}
  function extension(f:File){const x=f.name.split('.').pop()?.toLowerCase();if(x&&/^[a-z0-9]+$/.test(x))return x;return f.type==='image/png'?'png':'jpg'}
  async function upload(userId:string,projectId:string,file:File,kind:'reference'|'client',index=0){const bucket=kind==='reference'?'reference-images':'client-images';const path=`${userId}/${projectId}/${kind}-${index}-${crypto.randomUUID()}.${extension(file)}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(error)throw error;const {error:imageError}=await supabase.from('project_images').insert({user_id:userId,project_id:projectId,kind,storage_path:path,mime_type:file.type||null});if(imageError)throw imageError;return {bucket,path}}
  async function signed(bucket:string,path:string){const {data,error}=await supabase.storage.from(bucket).createSignedUrl(path,3600);if(error||!data?.signedUrl)throw error??new Error('Não foi possível preparar a imagem para a IA.');return data.signedUrl}
  async function generateEnsaio(){setMessage('');setResultImage(null);if(!referenceFile)return setMessage('Selecione a foto de referência.');if(!clientFiles.length)return setMessage('Adicione pelo menos uma foto da cliente.');if(!consent)return setMessage('Confirme que a cliente é adulta e autorizou o uso das imagens.');setLoading(true);
    try{const {data:userData,error:userError}=await supabase.auth.getUser();if(userError||!userData.user){router.push('/login');return}const userId=userData.user.id;
      setMessage('Salvando ensaio e enviando fotos...');const {data:project,error:projectError}=await supabase.from('projects').insert({user_id:userId,title:'Novo ensaio',edit_mode:editMode,instructions:instructions.trim()||null,status:'processing',adult_confirmed:true,consent_confirmed:true,consent_recorded_at:new Date().toISOString()}).select('id').single();if(projectError||!project)throw projectError??new Error('Não foi possível criar o ensaio.');
      const ref=await upload(userId,project.id,referenceFile,'reference');const clients=[];for(let i=0;i<clientFiles.length;i++)clients.push(await upload(userId,project.id,clientFiles[i],'client',i+1));
      setMessage('Gerando imagem com IA... Isso pode levar alguns instantes.');const imageUrls=[await signed(ref.bucket,ref.path)];for(const c of clients)imageUrls.push(await signed(c.bucket,c.path));
      const prompt=instructions.trim()||'Recrie a composição, pose, enquadramento e iluminação da referência, preservando fielmente a identidade facial da cliente.';
      const response=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,imageUrls,editMode})});const body=await response.json();if(!response.ok)throw new Error(body?.error||'Falha ao gerar a imagem.');if(!body?.imageUrl)throw new Error('A IA não retornou uma imagem.');
      setResultImage(body.imageUrl);setMessage('Imagem gerada com sucesso.');await supabase.from('projects').update({status:'completed'}).eq('id',project.id);
    }catch(error){const text=error instanceof Error?error.message:'Erro inesperado.';setMessage(`Não foi possível gerar o ensaio: ${text}`)}finally{setLoading(false)}}
  return <main className="container"><header><div><span className="badge">STUDIO AI</span><h1>Novo ensaio</h1><p>Use uma fotografia como referência e prepare a edição da sua cliente.</p></div></header>
    <section className="grid"><article className="card"><span className="step">01</span><h2>Foto de referência</h2><p>Pose, composição, iluminação, figurino ou cenário desejado.</p><label className={`upload ${reference?'hasPreview':''}`}>{reference?<img className="imagePreview" src={reference} alt="Prévia da foto de referência"/>:<span>+ Selecionar referência</span>}<input type="file" accept="image/*" onChange={chooseReference}/></label>{reference&&<p className="uploadHint">Clique na imagem para trocar a referência.</p>}</article>
    <article className="card"><span className="step">02</span><h2>Fotos da cliente</h2><p>Adicione de 1 a 5 fotos nítidas para preservar melhor a identidade facial.</p><label className={`upload ${clientPhotos.length?'hasPreview':''}`}>{clientPhotos.length?<div className="previewGrid">{clientPhotos.map((src,i)=><img className="clientPreview" src={src} alt={`Foto da cliente ${i+1}`} key={src}/>)}</div>:<span>+ Adicionar fotos</span>}<input type="file" accept="image/*" multiple onChange={chooseClientPhotos}/></label>{clientPhotos.length>0&&<p className="uploadHint">{clientPhotos.length} foto(s) selecionada(s). Clique nas imagens para trocar.</p>}</article></section>
    <section className="panel"><span className="step">03</span><h2>Tipo de edição</h2><div className="options">{modes.map(m=><button type="button" key={m.value} className={editMode===m.value?'active':''} onClick={()=>setEditMode(m.value)}>{m.label}</button>)}</div><label className="promptLabel">Instruções</label><textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Ex.: preserve fielmente a identidade da cliente e use a pose e iluminação da referência."/><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Confirmo que a cliente é adulta e autorizou o uso das imagens.</label>{message&&<div className="statusMessage" role="status">{message}</div>}<button type="button" className="generate" disabled={loading} onClick={generateEnsaio}>{loading?'Gerando ensaio...':'Gerar ensaio'}</button>{resultImage&&<div style={{marginTop:24}}><h2>Resultado</h2><img src={resultImage} alt="Resultado gerado pela IA" style={{width:'100%',maxHeight:900,objectFit:'contain',borderRadius:14,background:'#0d0d0f'}}/></div>}</section></main>
}
